### ISSUE TITLE
Strange error on testing

### ISSUE THREAD

**Issue by haslinger** [Hobo/hobo_paperclip#2]
In a test, i have been running for months, I suddenly get a strange error:

```
6) Sales::DownloadsController crud actions POST #create moves to photo if document is a photo
     Failure/Error: post :create, download: attributes_for(:download, photo: nil,
     Errno::EISDIR:
       Is a directory @ unlink_internal - /media/Storage/rails/mercator/public
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/paperclip-4.3.0/lib/paperclip/storage/filesystem.rb:64:in `block in flush_deletes'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/paperclip-4.3.0/lib/paperclip/storage/filesystem.rb:61:in `each'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/paperclip-4.3.0/lib/paperclip/storage/filesystem.rb:61:in `flush_deletes'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/paperclip-4.3.0/lib/paperclip/attachment.rb:239:in `save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/paperclip-4.3.0/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:427:in `_run__4433695164598672192__save__callbacks'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:302:in `create_or_update'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/persistence.rb:103:in `save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/validations.rb:51:in `save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/attribute_methods/dirty.rb:32:in `save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:327:in `with_transaction_returning_status'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:270:in `block in save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:285:in `rollback_active_record_state!'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/transactions.rb:269:in `save'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/hobo-2.1.1/lib/hobo/model/permissions.rb:191:in `block in user_update_attributes'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/hobo-2.1.1/lib/hobo/model/permissions.rb:167:in `with_acting_user'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/hobo-2.1.1/lib/hobo/model/permissions.rb:189:in `user_update_attributes'
     # /home/stefan/.rvm/gems/ruby-2.1.5/gems/hobo-2.1.1/lib/hobo/controller/model.rb:549:in `hobo_create'
     # ./app/controllers/sales/downloads_controller.rb:32:in `create'
```

which has maybe something to do with the fact, that there is a symlink in the path to my hobo app.

**Comment by haslinger** [comment]
Ok, this is a Problem with Paperclip 4.3.0, going back to Paperclip 4.2.1 solves this.

Actually when Paperclip tries to delete the old file, it just gets the path down to public, tries to delete it as a file and fails.
